debug: true

server:
  port: 9096

spring:
  data:
    mongodb:
      uri: mongodb://mongo-server:27017/deliflow-gocd-agent-manager
    mongo:
      repositories:
        enabled: true

rancher:
  uri: http://rancher-server:8080
  accessSecret: _some_access_key_
  secretKey: _some_secret_key_

gocd:
  uri: http://gocd-server:8153/go
  username: admin
  password: badger
  agentManager:
    agentEnvironment: Default
    agentStack: leansw-go-agents
    managedServiceResource: dynamic-manage-agent
    minIdles: 1
    maxInstances: 99
    scaleStep: 1

eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000

